# Generated by Django 3.0.2 on 2020-05-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200528_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='customize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordername', models.CharField(max_length=30)),
                ('orderdate', models.CharField(max_length=30)),
                ('changes', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
