# Generated by Django 3.0.2 on 2020-05-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200531_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='customize',
            name='phno',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customize',
            name='changes',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customize',
            name='orderdate',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customize',
            name='ordername',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
